export const data = {
  "indexCitys": {
    "当前定位城市": {
      label: '定位',
      data: [{
        "id": "1796",
        "code": "1796",
        "name": "福泉市",
        "name_en": "fuquan"
      }]
    },
    "热门": {
      style: 'grid',
      data: [{
        "id": "1796",
        "code": "1796",
        "name": "福泉市",
        "name_en": "fuquan"
      }, {
        "id": "2244",
        "code": "2244",
        "name": "阜康市",
        "name_en": "fukang"
      }, {
        "id": "3601",
        "code": "3601",
        "name": "富春江",
        "name_en": "fuchunjiang"
      }, {
        "id": "58",
        "code": "58",
        "name": "鞍山",
        "name_en": "anshan"
      }, {
        "id": "261",
        "code": "261",
        "name": "安顺",
        "name_en": "anshun"
      }, {
        "id": "288",
        "code": "288",
        "name": "阿里",
        "name_en": "ali"
      }, {
        "id": "1145",
        "code": "1145",
        "name": "安丘市",
        "name_en": "anqiu"
      }, {
        "id": "58",
        "code": "58",
        "name": "鞍山",
        "name_en": "anshan"
      }, {
        "id": "261",
        "code": "261",
        "name": "安顺",
        "name_en": "anshun"
      }, {
        "id": "288",
        "code": "288",
        "name": "阿里",
        "name_en": "ali"
      }, {
        "id": "1145",
        "code": "1145",
        "name": "安丘市",
        "name_en": "anqiu"
      }, {
        "id": "58",
        "code": "58",
        "name": "鞍山",
        "name_en": "anshan"
      }, {
        "id": "261",
        "code": "261",
        "name": "安顺",
        "name_en": "anshun"
      }, {
        "id": "288",
        "code": "288",
        "name": "阿里",
        "name_en": "ali"
      }, {
        "id": "1145",
        "code": "1145",
        "name": "安丘市",
        "name_en": "anqiu"
      }]
    },
    "A": {
      style: 'line',
      data: [{
        "id": "57",
        "code": "57",
        "name": "阿拉善",
        "name_en": "alashan"
      }, {
        "id": "58",
        "code": "58",
        "name": "鞍山",
        "name_en": "anshan"
      }, {
        "id": "261",
        "code": "261",
        "name": "安顺",
        "name_en": "anshun"
      }, {
        "id": "288",
        "code": "288",
        "name": "阿里",
        "name_en": "ali"
      }, {
        "id": "1145",
        "code": "1145",
        "name": "安丘市",
        "name_en": "anqiu"
      }, {
        "id": "1332",
        "code": "1332",
        "name": "安陆市",
        "name_en": "anlu"
      }, {
        "id": "1815",
        "code": "1815",
        "name": "安宁市",
        "name_en": "anning"
      }, {
        "id": "2213",
        "code": "2213",
        "name": "阿克苏市",
        "name_en": "akesu"
      }]
    },
    "B": {
      style: 'line',
      data: [{
        "id": "57",
        "code": "57",
        "name": "阿拉善",
        "name_en": "alashan"
      }, {
        "id": "58",
        "code": "58",
        "name": "鞍山",
        "name_en": "anshan"
      }, {
        "id": "261",
        "code": "261",
        "name": "安顺",
        "name_en": "anshun"
      }, {
        "id": "288",
        "code": "288",
        "name": "阿里",
        "name_en": "ali"
      }, {
        "id": "1145",
        "code": "1145",
        "name": "安丘市",
        "name_en": "anqiu"
      }, {
        "id": "1332",
        "code": "1332",
        "name": "安陆市",
        "name_en": "anlu"
      }, {
        "id": "1815",
        "code": "1815",
        "name": "安宁市",
        "name_en": "anning"
      }, {
        "id": "2213",
        "code": "2213",
        "name": "阿克苏市",
        "name_en": "akesu"
      }]
    },
    "C": {
      style: 'line',
      data: [{
        "id": "57",
        "code": "57",
        "name": "阿拉善",
        "name_en": "alashan"
      }, {
        "id": "58",
        "code": "58",
        "name": "鞍山",
        "name_en": "anshan"
      }, {
        "id": "261",
        "code": "261",
        "name": "安顺",
        "name_en": "anshun"
      }, {
        "id": "288",
        "code": "288",
        "name": "阿里",
        "name_en": "ali"
      }, {
        "id": "1145",
        "code": "1145",
        "name": "安丘市",
        "name_en": "anqiu"
      }, {
        "id": "1332",
        "code": "1332",
        "name": "安陆市",
        "name_en": "anlu"
      }, {
        "id": "1815",
        "code": "1815",
        "name": "安宁市",
        "name_en": "anning"
      }, {
        "id": "2213",
        "code": "2213",
        "name": "阿克苏市",
        "name_en": "akesu"
      }]
    }           
  }
};